### ISSUE TITLE
Release the package to Maven Central or equivalent instead of self hosted for backup

### ISSUE THREAD

**Issue by stevefan1999-personal** [DevSrSouza/KotlinBukkitAPI#11]
Hi, just to say you're doing a very great job, but your server is inaccessible sometimes and I'd like to have a setback available.

**Comment by DevSrSouza** [comment]
I will see if I can publish it to a JCenter repository too.

Give you a feedback late this week.

**Comment by DevSrSouza** [comment]
Hi @stevefan1999-personal, I finally publish a backup repository for KotlinBukkitAPI, I'm using `oss.frog.org`. Hope this help you!

```kotlin
repositories {
  maven("https://oss.jfrog.org/oss-snapshot-local/")
  maven("http://nexus.okkero.com/repository/maven-releases/") //skedule
  maven("https://repo.codemc.org/repository/maven-public") //bstats
}
```
