### ISSUE TITLE
[Commands] add support for handling exceptions

### ISSUE THREAD

**Issue by Cubxity** [DevSrSouza/KotlinBukkitAPI#14]
## Description
If the command executor throws an error, executors will not run anymore due to the coroutineScope being canceled.

## Proposal
I propose that you should catch the executor block and have an exception handler for the command that is also used by its children and have a default exception handler, something like Bukkit's "An internal error occurred whilst executing this command".

**Comment by DevSrSouza** [comment]
Thanks for reporting that.
Yes, I found that all of KotlinBukkitAPI usage of Coroutines was kinda wrong, and, one failure causes to cancel everything that is already running.

I fix that with SupervisorJob in the last commit. (fca8a3a6770cb9257b6f7dd1d06f4769aaaf3495)

About error handling of any exceptions, this is something that I was thinking about it and I will work on it and give a feedback in what the API I'm planning.

**Comment by DevSrSouza** [comment]
Hi @Cubxity, I add an error handling, you can find the usage [here](https://github.com/DevSrSouza/KotlinBukkitAPI/wiki/Command-Fail#error-handling).

Could you give me a feedback? Any idea in that I can improve on it?

**Comment by Cubxity** [comment]
> Hi @Cubxity, I add an error handling, you can find the usage [here](https://github.com/DevSrSouza/KotlinBukkitAPI/wiki/Command-Fail#error-handling).
> 
> Could you give me a feedback? Any idea in that I can improve on it?

Looks great. By the way, don't you need '+' operator for translating chat code?

**Comment by DevSrSouza** [comment]
@Cubxity Yes, I forgot it, you can use the plus operator for translating color codes or use the extension `translateColor()`
