### ISSUE TITLE
Create a discord channel

### ISSUE THREAD

**Issue by zoeleu** [DevSrSouza/KotlinBukkitAPI#18]
make a discord guild (better than twitter for support)

**Comment by SrGaabriel** [comment]
It's on @DevSrSouza plans.

**Comment by DevSrSouza** [comment]
Yes, I'm working on with, I guess this week I will publish it into the README and here as well 😊.

**Comment by DevSrSouza** [comment]
Hey @matteoturini, I start one, need to configure it better, but is here to support you folks

https://discord.gg/HhucBqk

**Comment by SrGaabriel** [comment]
@matteoturini i think you can close this.
