### ISSUE TITLE
Command  Arguments  material()

### ISSUE THREAD

**Issue by smallshen** [DevSrSouza/KotlinBukkitAPI#19]
in Command  Arguments, there is a material() function to get material

it would be better to change all letter to uppercase when checking, due to all materials in Material enum is uppercase, and I think forName() method is case sensitive.

for example: 
"/mycommand air" doesn't work, but "/mycommand AIR" works

**Comment by DevSrSouza** [comment]
I did a fix, tkx for reporting :D

**Comment by smallshen** [comment]
Thank you
