### ISSUE TITLE
Cannot build latest version.

### ISSUE THREAD

**Issue by tomocrafter** [DevSrSouza/KotlinBukkitAPI#5]
![image](https://user-images.githubusercontent.com/10905364/73134550-f80cd600-407a-11ea-8db9-df8cba7b1a14.png)

Added bstats to this plugin as dependency, and now I cannot build it.

**Comment by DevSrSouza** [comment]
Hi, @tomocrafter, you can get the latest build from my Jenkins now, no need to build your self.

http://jenkins.devsrsouza.com.br

If you are building the project by yourself for use as a dependency in your plugins, now the project has a maven repository that you can find in the README.
